package introduction;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class AssignmentAutoGeneratedDropDown {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.chrome.driver","C:\\Users\\Ajay\\Documents\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		driver.manage().window().maximize();
		driver.get("https://www.rahulshettyacademy.com/AutomationPractice/");
		driver.findElement(By.id("autocomplete")).sendKeys("IND");
		try {
			Thread.sleep(2000L);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		driver.findElement(By.id("autocomplete")).sendKeys(Keys.DOWN);
		System.out.println(driver.findElement(By.id("autocomplete")).getText());
		JavascriptExecutor js = (JavascriptExecutor)driver;
		String s= "return document.getElementById(\"autocomplete\").value;"; 
		String text = (String) js.executeScript(s);
		System.out.println("executor script"+text);
		int i =0;
		while(!text.equalsIgnoreCase("Indonesia"))
		{
			i++;
		driver.findElement(By.id("autocomplete")).sendKeys(Keys.DOWN);
		text = (String) js.executeScript(s);
		System.out.println(text);
		if (i>5)
		{
			break;
		}
		
		}
		
		if (i>5)
		{
			System.out.println("element not found");
		}
		else
		{
			System.out.println("element found"+text);
		}
		
		
		
		
	}

}
